// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0
// source: words.sql

package words

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const create = `-- name: create :one
INSERT INTO words
    (word, transcription, language_id)
VALUES
    ($1, $2, $3)
RETURNING id, number, word, transcription, language_id, word_ts, created_at, updated_at
`

type createParams struct {
	Word          string      `db:"word"`
	Transcription pgtype.Text `db:"transcription"`
	LanguageID    uint64      `db:"language_id"`
}

func (q *Queries) create(ctx context.Context, arg createParams) (Word, error) {
	row := q.db.QueryRow(ctx, create, arg.Word, arg.Transcription, arg.LanguageID)
	var i Word
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Word,
		&i.Transcription,
		&i.LanguageID,
		&i.WordTs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
