logger:
  mode: dev
  log-format: json
  log-level: debug
  datetime-format: "2006-01-02 15:04:05"
  use-timestamp: false
  include-caller-method: true

storage:
  postgres:
    connection-string: "postgres://postgres:postgres@127.0.0.1:5432/words?sslmode=disable"
    max-retries: 5
    retry-delay: 10s
    auto-migrate: true
    dialect: postgres
    migration-directory: "dbschema/migrations"
    migration-direction: "up"


delivery:
  http-server:
    log-requests: true
    listen-address: 0.0.0.0:10001
    read-timeout: 100s
    write-timeout: 100s
    body-size-limit: 10128
    graceful-timeout: 60
