// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0
// source: languages.sql

package languages

import (
	"context"
)

const create = `-- name: create :one
INSERT INTO languages
    (language_name, code)
VALUES
    ($1, $2)
RETURNING id, language_name, code, created_at, updated_at
`

type createParams struct {
	LanguageName string `db:"language_name"`
	Code         string `db:"code"`
}

func (q *Queries) create(ctx context.Context, arg createParams) (Language, error) {
	row := q.db.QueryRow(ctx, create, arg.LanguageName, arg.Code)
	var i Language
	err := row.Scan(
		&i.ID,
		&i.LanguageName,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
