// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0
// source: description.sql

package description

import (
	"context"

	"github.com/google/uuid"
)

const create = `-- name: create :one
INSERT INTO description
    (word_id, description, level)
VALUES
    ($1, $2, $3)
RETURNING id, number, word_id, description, level, created_at, updated_at
`

type createParams struct {
	WordID      uuid.UUID     `db:"word_id"`
	Description string        `db:"description"`
	Level       LanguageLevel `db:"level"`
}

func (q *Queries) create(ctx context.Context, arg createParams) (Description, error) {
	row := q.db.QueryRow(ctx, create, arg.WordID, arg.Description, arg.Level)
	var i Description
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.WordID,
		&i.Description,
		&i.Level,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
