// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0
// source: groups.sql

package groups

import (
	"context"
)

const create = `-- name: create :one
INSERT INTO groups
    (name)
VALUES
    ($1)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) create(ctx context.Context, name string) (Group, error) {
	row := q.db.QueryRow(ctx, create, name)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
